### ISSUE TITLE
Docker compose内でのAPIからDBへの接続に起動時に失敗する

### ISSUE THREAD

**Issue by a163236** [Akitsu-Lab/chat-db#2]
# Problem
chat-dbのdocker-compose.ymlからdbとapiを起動しようとしてて、dbの方は問題ないが、apiの方がエラーになる。

# Branch
`build_environment branch`
https://github.com/Akitsu-Lab/chat-api/tree/build_environment
https://github.com/Akitsu-Lab/chat-db/tree/build_environment

# Repro steps

1. checkout to `build_environment` in chat-api
2. checkout to `build_environment` in chat-db
3. cd chat-db
4. `docker compose up --build -d`
 

# Error
```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-08-16T14:54:27.577608384Z 2024-08-16T14:54:27.571Z ERROR 1 --- [chat-api] [           main] o.s.boot.SpringApplication               : Application run failed
2024-08-16T14:54:27.577634218Z 
2024-08-16T14:54:27.577638426Z org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcMappingContext' defined in class path resource [org/springframework/boot/autoconfigure/data/jdbc/JdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration.class]: Unsatisfied dependency expressed through method 'jdbcMappingContext' parameter 1: Error creating bean with name 'jdbcCustomConversions' defined in class path resource [org/springframework/boot/autoconfigure/data/jdbc/JdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration.class]: Failed to instantiate [org.springframework.data.jdbc.core.convert.JdbcCustomConversions]: Factory method 'jdbcCustomConversions' threw exception with message: Error creating bean with name 'jdbcDialect' defined in class path resource [org/springframework/boot/autoconfigure/data/jdbc/JdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration.class]: Failed to instantiate [org.springframework.data.relational.core.dialect.Dialect]: Factory method 'jdbcDialect' threw exception with message: Failed to obtain JDBC Connection
2024-08-16T14:54:27.577644134Z 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577646551Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:542) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577649634Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577650759Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577762134Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577786384Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577816176Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577824051Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577831468Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577839218Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577847176Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577906384Z 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971) ~[spring-context-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577919343Z 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625) ~[spring-context-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.577928009Z 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.577935718Z 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.577939176Z 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.577941301Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.577943509Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.577945551Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.577948509Z 	at com.akitsu_lab.chat_api.ChatApiApplication.main(ChatApiApplication.java:10) ~[!/:0.0.1-SNAPSHOT]
2024-08-16T14:54:27.577950759Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
2024-08-16T14:54:27.577952843Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
2024-08-16T14:54:27.577954801Z 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[chat-api-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-08-16T14:54:27.577957759Z 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[chat-api-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-08-16T14:54:27.577965051Z 	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[chat-api-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
2024-08-16T14:54:27.578024593Z Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdbcCustomConversions' defined in class path resource [org/springframework/boot/autoconfigure/data/jdbc/JdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration.class]: Failed to instantiate [org.springframework.data.jdbc.core.convert.JdbcCustomConversions]: Factory method 'jdbcCustomConversions' threw exception with message: Error creating bean with name 'jdbcDialect' defined in class path resource [org/springframework/boot/autoconfigure/data/jdbc/JdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration.class]: Failed to instantiate [org.springframework.data.relational.core.dialect.Dialect]: Factory method 'jdbcDialect' threw exception with message: Failed to obtain JDBC Connection
2024-08-16T14:54:27.578035009Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578036634Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:485) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578038093Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578040343Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578041468Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578042551Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578043634Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578044676Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578045718Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578046759Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578047801Z 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578048843Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578049926Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578051009Z 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578052843Z 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578053884Z 	... 24 common frames omitted
2024-08-16T14:54:27.578055218Z Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.jdbc.core.convert.JdbcCustomConversions]: Factory method 'jdbcCustomConversions' threw exception with message: Error creating bean with name 'jdbcDialect' defined in class path resource [org/springframework/boot/autoconfigure/data/jdbc/JdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration.class]: Failed to instantiate [org.springframework.data.relational.core.dialect.Dialect]: Factory method 'jdbcDialect' threw exception with message: Failed to obtain JDBC Connection
2024-08-16T14:54:27.578057009Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578058093Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578059093Z 	... 38 common frames omitted
2024-08-16T14:54:27.578062718Z Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdbcDialect' defined in class path resource [org/springframework/boot/autoconfigure/data/jdbc/JdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration.class]: Failed to instantiate [org.springframework.data.relational.core.dialect.Dialect]: Factory method 'jdbcDialect' threw exception with message: Failed to obtain JDBC Connection
2024-08-16T14:54:27.578066884Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578071134Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578075634Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578079509Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578082009Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578083426Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578084509Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578085509Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578086551Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578088884Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:225) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578089926Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1323) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578090926Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1284) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578091968Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:486) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578093009Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:341) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578094009Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:334) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578095051Z 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1261) ~[spring-context-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578096051Z 	at org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration.jdbcCustomConversions(AbstractJdbcConfiguration.java:154) ~[spring-data-jdbc-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.578097343Z 	at org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration.jdbcCustomConversions(JdbcRepositoriesAutoConfiguration.java:127) ~[spring-boot-autoconfigure-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.578098509Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
2024-08-16T14:54:27.578099509Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
2024-08-16T14:54:27.578100468Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578103926Z 	... 39 common frames omitted
2024-08-16T14:54:27.578104801Z Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.relational.core.dialect.Dialect]: Factory method 'jdbcDialect' threw exception with message: Failed to obtain JDBC Connection
2024-08-16T14:54:27.578106009Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578109593Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578114051Z 	... 59 common frames omitted
2024-08-16T14:54:27.578116259Z Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
2024-08-16T14:54:27.578119384Z 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:84) ~[spring-jdbc-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578123384Z 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:342) ~[spring-jdbc-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578127218Z 	at org.springframework.data.jdbc.repository.config.DialectResolver$DefaultDialectProvider.getDialect(DialectResolver.java:108) ~[spring-data-jdbc-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.578131259Z 	at org.springframework.data.jdbc.repository.config.DialectResolver.lambda$getDialect$0(DialectResolver.java:78) ~[spring-data-jdbc-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.578135426Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
2024-08-16T14:54:27.578137801Z 	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685) ~[na:na]
2024-08-16T14:54:27.578140759Z 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
2024-08-16T14:54:27.578144676Z 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
2024-08-16T14:54:27.578145718Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
2024-08-16T14:54:27.578148759Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
2024-08-16T14:54:27.578152468Z 	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
2024-08-16T14:54:27.578155926Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
2024-08-16T14:54:27.578158759Z 	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[na:na]
2024-08-16T14:54:27.578160593Z 	at org.springframework.data.jdbc.repository.config.DialectResolver.getDialect(DialectResolver.java:80) ~[spring-data-jdbc-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.578164426Z 	at org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration.jdbcDialect(AbstractJdbcConfiguration.java:227) ~[spring-data-jdbc-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.578168426Z 	at org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration$SpringBootJdbcConfiguration.jdbcDialect(JdbcRepositoriesAutoConfiguration.java:151) ~[spring-boot-autoconfigure-3.3.2.jar!/:3.3.2]
2024-08-16T14:54:27.578170926Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
2024-08-16T14:54:27.578175218Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
2024-08-16T14:54:27.578178259Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578180926Z 	... 60 common frames omitted
2024-08-16T14:54:27.578184634Z Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
2024-08-16T14:54:27.578187593Z 
2024-08-16T14:54:27.578191051Z The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2024-08-16T14:54:27.578196759Z 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578200468Z 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578204093Z 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578208093Z 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578212051Z 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578216134Z 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578219759Z 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137) ~[HikariCP-5.1.0.jar!/:na]
2024-08-16T14:54:27.578221384Z 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) ~[HikariCP-5.1.0.jar!/:na]
2024-08-16T14:54:27.578224426Z 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[HikariCP-5.1.0.jar!/:na]
2024-08-16T14:54:27.578227926Z 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) ~[HikariCP-5.1.0.jar!/:na]
2024-08-16T14:54:27.578231384Z 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550) ~[HikariCP-5.1.0.jar!/:na]
2024-08-16T14:54:27.578234884Z 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98) ~[HikariCP-5.1.0.jar!/:na]
2024-08-16T14:54:27.578238093Z 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:111) ~[HikariCP-5.1.0.jar!/:na]
2024-08-16T14:54:27.578239593Z 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160) ~[spring-jdbc-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578243926Z 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118) ~[spring-jdbc-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578246301Z 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81) ~[spring-jdbc-6.1.11.jar!/:6.1.11]
2024-08-16T14:54:27.578247259Z 	... 78 common frames omitted
2024-08-16T14:54:27.578248093Z Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
2024-08-16T14:54:27.578736093Z 
2024-08-16T14:54:27.578741593Z The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2024-08-16T14:54:27.578743051Z 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[na:na]
2024-08-16T14:54:27.578744301Z 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[na:na]
2024-08-16T14:54:27.578745259Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[na:na]
2024-08-16T14:54:27.578750509Z 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578751676Z 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:104) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578752718Z 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:149) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578753718Z 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:165) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578754843Z 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:88) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578755926Z 	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578756884Z 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:935) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578757843Z 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:805) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578758801Z 	... 91 common frames omitted
2024-08-16T14:54:27.578759676Z Caused by: java.net.ConnectException: Connection refused
2024-08-16T14:54:27.578760551Z 	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
2024-08-16T14:54:27.578761426Z 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[na:na]
2024-08-16T14:54:27.578763718Z 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[na:na]
2024-08-16T14:54:27.578765843Z 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[na:na]
2024-08-16T14:54:27.578766759Z 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
2024-08-16T14:54:27.578770259Z 	at java.base/java.net.Socket.connect(Socket.java:751) ~[na:na]
2024-08-16T14:54:27.578773843Z 	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578777968Z 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:62) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
2024-08-16T14:54:27.578781009Z 	... 94 common frames omitted
2024-08-16T14:54:27.578784093Z 
```

**Comment by SOTAkkkk** [comment]
これらのPRで解決
https://github.com/Akitsu-Lab/chat-db/pull/3
https://github.com/Akitsu-Lab/chat-api/pull/5
